### PR TITLE
Add workflow to update issue and PR status on GH project board

### PR DESCRIPTION
**Pull request by t1m0thyj**
See https://github.com/zowe/vscode-extension-for-zowe/pull/2654 for details

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]

**Review by JillieBeanSim — COMMENTED** [review]
@t1m0thyj is the .husky/commit-msg empty file a mistake?

**Review by traeok — APPROVED** [review]
Thanks @t1m0thyj

**Comment by t1m0thyj** [comment]
> @t1m0thyj is the .husky/commit-msg empty file a mistake?

Not sure why GitHub shows the file as empty, this confused me too 😋  The file isn't empty in `main` branch, and the only change made to the file in this PR was `chmod +x` to make it executable. It seems like GitHub shows an empty diff when the only change to a file is the permission bits?

**Comment by zFernand0** [comment]
Merging! 😋

**Pull request merged**
